# Generated by Django 5.1.7 on 2025-03-20 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("duracion", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField()),
                ("categoria", models.CharField(max_length=100)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[("OYM", "OYM"), ("LABORATORIO", "LABORATORIO")],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contraseña", models.CharField(max_length=128)),
                (
                    "rol",
                    models.CharField(
                        choices=[("admin", "Admin"), ("usuario", "Usuario")],
                        default="usuario",
                        max_length=10,
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[("OYM", "OYM"), ("LABORATORIO", "LABORATORIO")],
                        default="OYM",
                        max_length=15,
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        choices=[
                            ("Risaralda", "Risaralda"),
                            ("Quindio", "Quindio"),
                            ("Caldas", "Caldas"),
                        ],
                        default="Risaralda",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opcion", models.CharField(max_length=255)),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cuestionario.pregunta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cuestionario.examen",
                    ),
                ),
                (
                    "opcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cuestionario.opcion",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cuestionario.pregunta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="examen",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cuestionario.usuario"
            ),
        ),
    ]
